tasks:
  - init: |
      sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
      eval $(gp env -e PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH)
      wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb 
      sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      bash <(curl -sSf https://sugar.metaplex.com/install.sh)